# Generated by Django 2.2.5 on 2019-10-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('length', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Length[CM]')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Width[CM]')),
                ('thickness', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Thickness[MM]')),
                ('stock_units', models.PositiveIntegerField(default=0)),
                ('ordered', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Price[NIS]')),
                ('image', models.ImageField(blank=True, default='logo-icon.png', null=True, upload_to='products')),
                ('description', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Category')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Processing')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Stone')),
            ],
        ),
    ]
